### PR TITLE
Add More Logos and update social media card (#695 )

### PR DESCRIPTION
**Pull request by dquach217**
- Update Social Media Card to 2018-2019
- Add Partners Logo
- Update some logos to be white
- Add more sponsors logo

### CODE REVIEW

**Comment by dquach217** [comment]
@sman591 Updated the social media card to be a jpg

**Comment by sman591** [comment]
@dquach217 text looks kind of off

brickhack_card

**Comment by dquach217** [comment]
@sman591 got the fixed jpg

**Comment by sman591** [comment]
🎉

**Pull request merged**
