### PR TITLE
BH8 - Outlined logo for application portal

### LINKED ISSUE #1260: Uploading outlined logo
Keeping this seperate from sponsorship issue, but trying to include it in that release
Basically just adding an outlined version of the bh logo for use on the application portal against that default grey navbar color. Using the precedent that we host logos used in the application portal on here (at least, that's what I was seeing in chris's setup)

### PR DESCRIPTION
**Pull request by sjmiller7**
Fixes #1260 to solve a color bleed issue with the logo's dark blue against the nav in the application portal without having to restyle the entire portal

### CODE REVIEW

**Comment by skyegallup** [comment]
It looks like the first two commits here are shared with `bh-1258`. Did you mean to merge this into `bh-1258`?

**Review by skyegallup — DISMISSED** [review]
Ignoring the strangeness with the extra commits: looks good! (not that there's much to look at - it's just adding an image)

**Comment by sjmiller7** [comment]
I think I goofed and didn't switch branches before making a new one. @skyegallup will it be fine if I just merge this after merging the other one or should I redo this?

**Comment by skyegallup** [comment]
> will it be fine if I just merge this after merging the other one or should I redo this?

Yeah, that's fine!

**Review by skyegallup — APPROVED** [review]

**Pull request merged**
