### PR TITLE
BrickHack8 - Sponsorship Logos

### PR DESCRIPTION
**Pull request by sjmiller7**
Waiting on approval from multiple teams

Then unnecessary sections will be commented out and confirmed sponsors will be added before pushing to live

### CODE REVIEW

**Review by peterkos — DISMISSED** [review]
LGTM! Sizing looks really good and the hover effects are a nice touch. Responsiveness is good too!

**Review by skyegallup — APPROVED** [review]
~~CSS grid instead of flexbox 🤮~~

In all seriousness, the responsiveness works well. I'm curious as to why you chose grid over flexbox here, but I won't complain because it *does* work quite well.

**Comment by sjmiller7** [comment]
> ~CSS grid instead of flexbox 🤮~
> 
> In all seriousness, the responsiveness works well. I'm curious as to why you chose grid over flexbox here, but I won't complain because it _does_ work quite well.

Oops! Had leftover grid stuff in there from when I started it (initially did grid because I thought bh7 did but those classes were just *named* grid)
It's fixed now

Should be noted moving forward that we can't use `gap` shorthand property because Safari does not support it when there are multiple columns. Grids and Flexes should use both `grid-gap` and `row-gap` as a replacement

**Comment by skyegallup** [comment]
Added sponsor logs for initial push and changes requested by design team, so we should be good for review:

image

I'm afraid that the StickerMule logo is a bit small due to the padding that's baked into their SVG (and that their style guide asks us to not remove). Perhaps we can scale it up by 20% in CSS?

**Comment by sjmiller7** [comment]
>  Perhaps we can scale [stickermule] up by 20% in CSS?

I would say that even upping it to 200px width looks better. Figma is just so big in comparison because of how they shape their logo.

I'm wondering if it's worth rebasing logo size to base on height? Here's a sample of what that looks like:
image

**Comment by sjmiller7** [comment]
Adding here so I don't forget: https://www.notion.so/brickhackclub/web-Prizes-Sponsorship-1ed03d9e0f1a42b6bfabd3ca5f7f261a

**Comment by sjmiller7** [comment]
Note: Yes I know stickermule looks like theres more spacing before it but it's sticker mule brand guidelines and I'm not gonna bend over backwards to fix what they broke

**Review by skyegallup — APPROVED** [review]
👍 good divs

**Pull request merged**
